title: Botao Zhao
logo: /images/photo_circle.png
description: Passionate Aero/Mech/Robotics Engineer at the intersection of cutting-edge technology and healthcare in the medical devices industry.
show_downloads: true
theme: jekyll-theme-minimal
